### ISSUE TITLE
Woomer only takes up a quarter of the screen

### ISSUE THREAD

**Issue by NickMundel** [coffeeispower/woomer#14]
I installed woomer via the AUR and also tried compiling it directly, however there seems to a bug regarding the fullscreen of application.

![2024-10-25-095847_hyprshot](https://github.com/user-attachments/assets/46423957-3616-4bc7-a01c-b1c89a4b2971)

If you need any logs, just hit me up!

**Comment by coffeeispower** [comment]
Fun thing is i'm also using hyprland and i don't have that problem, although it is a older version of hyprland, it's 0.41 and since you're on arch linux you probably have the latest git commit installed.
Might be a bug in newer hyprland versions so i probably recomend you try reporting it to hyprland it self because it's a regression.

**Comment by NickMundel** [comment]
I believe I tracked it down to Scaling, in the Hyprland config i set it higher than one, which caused the window to scale proportional to that value. So it actually comes down to Raylib.  I'm working on a fix and keep you updated

**Comment by NickMundel** [comment]
I actually boiled it down to a scalling issue in Raylib. I'm working on a fix and if possible create a pull request
